"""modify CartItem table name

Revision ID: 2e319f2e6c40
Revises: 3ad91d713a9a
Create Date: 2024-05-15 21:22:45.972008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e319f2e6c40'
down_revision = '3ad91d713a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_cart_items_customer_id_customers')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_cart_items_item_id_items')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_cart_item_customer_id_customers'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='fk_cart_item_item_id_items'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart_items')
    # ### end Alembic commands ###
