"""Add item_idx column to OrderItem model class

Revision ID: f1b3fe74f013
Revises: 28cee044deb7
Create Date: 2024-05-20 11:45:20.274394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b3fe74f013'
down_revision = '28cee044deb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_idx', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('item_idx')

    # ### end Alembic commands ###
